name = "MyPackage"
uuid = "88ef53c0-2e51-4b6c-90ec-8f7df14ca16c"
authors = ["Steve Osazuwa"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
